import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('Village activity notifications are private and generated by participation', async () => {
  const migration = await read('supabase/migrations/202607310043_digital_village_completion.sql');
  assert.match(migration, /create table public\.village_notifications/);
  assert.match(migration, /recipient_id = auth\.uid\(\)/);
  assert.match(migration, /village_comment_notification/);
  assert.match(migration, /village_reaction_notification/);
  assert.match(migration, /mark_village_notifications_read/);
});

test('Community moderation is role protected and available from the Village Square', async () => {
  const migration = await read('supabase/migrations/202607310043_digital_village_completion.sql');
  const page = await read('src/pages/VillageSquare.tsx');
  const moderation = await read('src/pages/VillageModeration.tsx');
  const app = await read('src/App.tsx');
  assert.match(migration, /role in \('chairman', 'secretary_general', 'ipro', 'admin'\)/);
  assert.match(migration, /resolve_village_report/);
  assert.match(page, /postgres_changes/);
  assert.match(page, /Recent activity/);
  assert.match(moderation, /Village moderation/);
  assert.match(app, /dashboard\/village\/moderation/);
});
