import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import './ChairmanCertificateApproval.css';

type CertificateRow = { id:string; member_name:string; course_title:string; completed_lessons:number; quiz_score:number|null; final_assessment_score:number|null; practical_assignment:string|null; tutor_name:string|null; attendance_verified:boolean; completion_date:string|null; status:string; rejection_reason:string|null };

export function ChairmanCertificateApproval(){
  const [rows,setRows]=useState<CertificateRow[]>([]); const [chairman,setChairman]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [reasons,setReasons]=useState<Record<string,string>>({});
  async function load(){setLoading(true);const [access,queue]=await Promise.all([supabase.rpc('is_active_chairman'),supabase.rpc('chairman_certificate_queue')]);setChairman(Boolean(access.data));if(queue.error)setError('Certificate records could not be loaded.');else setRows((queue.data??[]) as CertificateRow[]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  async function decide(id:string,decision:'Approved'|'Rejected'){const reason=reasons[id]?.trim()||null;if(decision==='Rejected'&&!reason){setError('Enter a rejection reason before rejecting a certificate.');return}const {error:rpcError}=await supabase.rpc('decide_certificate',{certificate_id:id,decision,rejection_reason:reason});if(rpcError)setError(rpcError.message);else{setError('');await load()}}
  if(loading)return <section className="certificate-admin-state">Loading certificate approvals…</section>;
  return <section className="certificate-approval-page"><header><p className="eyebrow">Secure final authorization</p><h1>Chairman Certificate Approval</h1><p>{chairman?'Review tutor-verified course completions and make the final decision.':'Certificate records are view-only for your office.'}</p></header>{error&&<p className="dashboard-alert" role="alert">{error}</p>}<div className="certificate-queue">{rows.map(row=><article key={row.id}><div className="certificate-card-heading"><div><h2>{row.member_name}</h2><p>{row.course_title}</p></div><strong>{row.status}</strong></div><dl><div><dt>Completed lessons</dt><dd>{row.completed_lessons}</dd></div><div><dt>Quiz / final assessment</dt><dd>{row.quiz_score??'—'} / {row.final_assessment_score??'—'}%</dd></div><div><dt>Attendance</dt><dd>{row.attendance_verified?'Verified':'Not verified'}</dd></div><div><dt>Tutor verification</dt><dd>{row.tutor_name??'Awaiting verification'}</dd></div><div><dt>Completion date</dt><dd>{row.completion_date?new Date(row.completion_date).toLocaleDateString():'—'}</dd></div></dl><section><h3>Practical assignment</h3><p>{row.practical_assignment??'No assignment recorded.'}</p></section>{row.rejection_reason&&<p><strong>Rejection reason:</strong> {row.rejection_reason}</p>}{chairman&&row.status==='Pending Chairman Approval'&&<div className="certificate-actions"><label>Rejection reason<textarea value={reasons[row.id]??''} onChange={event=>setReasons({...reasons,[row.id]:event.target.value})}/></label><div><button className="primary-button" onClick={()=>void decide(row.id,'Approved')}>Approve</button><button className="secondary-button" onClick={()=>void decide(row.id,'Rejected')}>Reject</button></div></div>}</article>)}{rows.length===0&&<p>No certificate records are awaiting review.</p>}</div></section>
}
