import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { supabase } from '../lib/supabase';
import type { AssociationEvent, Attendance } from '../types/event';
import './EventsManagement.css';

type Member = { id: string; full_name: string; membership_number: string | null };
type AttendanceRow = Attendance & { profiles: Member | null };
const blank = { title: '', description: '', category: 'Meeting', starts: '', ends: '', venue: '', capacity: '' };

export function EventAdministration() {
  const [allowed, setAllowed] = useState<boolean | null>(null); const [events, setEvents] = useState<AssociationEvent[]>([]); const [members, setMembers] = useState<Member[]>([]); const [attendance, setAttendance] = useState<AttendanceRow[]>([]);
  const [selected, setSelected] = useState(''); const [form, setForm] = useState(blank); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const { data: authorized } = await supabase.rpc('can_manage_events'); setAllowed(Boolean(authorized)); if (!authorized) return;
    const [e, m, a] = await Promise.all([supabase.from('association_events').select('*').order('starts_at', { ascending: false }), supabase.from('profiles').select('id, full_name, membership_number').eq('is_active', true).order('full_name'), supabase.from('event_attendance').select('event_id, member_id, response, checked_in_at, profiles!event_attendance_member_id_fkey(id, full_name, membership_number)')]);
    if (e.error || m.error || a.error) setMessage('Event records could not be loaded.'); else { setEvents((e.data ?? []) as AssociationEvent[]); setMembers((m.data ?? []) as Member[]); setAttendance((a.data ?? []) as unknown as AttendanceRow[]); setSelected((current) => current || e.data?.[0]?.id || ''); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const selectedEvent = events.find((item) => item.id === selected); const rows = attendance.filter((item) => item.event_id === selected); const goingIds = new Set(rows.filter((item) => item.response === 'going').map((item) => item.member_id));
  const report = useMemo(() => ({ going: rows.filter((x) => x.response === 'going').length, declined: rows.filter((x) => x.response === 'not_going').length, attended: rows.filter((x) => x.checked_in_at).length }), [rows]);
  async function createEvent(event: FormEvent) { event.preventDefault(); setBusy(true); const { data: auth } = await supabase.auth.getUser(); const { error } = await supabase.from('association_events').insert({ title: form.title.trim(), description: form.description.trim(), category: form.category, starts_at: new Date(form.starts).toISOString(), ends_at: new Date(form.ends).toISOString(), venue: form.venue.trim(), capacity: form.capacity ? Number(form.capacity) : null, created_by: auth.user?.id }); setBusy(false); if (error) setMessage(error.message); else { setForm(blank); setMessage('Draft event created.'); void load(); } }
  async function setStatus(id: string, status: AssociationEvent['status']) { setBusy(true); const { error } = await supabase.from('association_events').update({ status }).eq('id', id); setBusy(false); setMessage(error ? error.message : `Event ${status}.`); if (!error) void load(); }
  async function checkIn(memberId: string, attended: boolean) { setBusy(true); const { error } = await supabase.rpc('set_event_check_in', { target_event_id: selected, target_member_id: memberId, attended }); setBusy(false); if (error) setMessage(error.message); else void load(); }
  if (allowed === null) return <section className="event-state">Checking event access…</section>;
  if (!allowed) return <section className="event-state"><div><h1>Access denied</h1><p>Event management is restricted to authorized officers.</p><a href="#/dashboard">Return to dashboard</a></div></section>;
  return <section className="event-admin-page"><header className="event-page-header"><div><p className="eyebrow">Executive administration</p><h1>Event Management</h1><p>Publish activities, manage RSVPs and record attendance.</p></div><a className="secondary-button" href="#/dashboard">Back to dashboard</a></header>{message && <p className="event-message" role="status">{message}</p>}
    <form className="event-form" onSubmit={createEvent}><h2>Create an event</h2><div className="event-form-grid"><label>Title<input required minLength={3} value={form.title} onChange={(e) => setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={(e) => setForm({...form,category:e.target.value})}><option>Meeting</option><option>Community service</option><option>Training</option><option>Fundraiser</option><option>Social</option></select></label><label>Starts<input required type="datetime-local" value={form.starts} onChange={(e) => setForm({...form,starts:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={form.ends} onChange={(e) => setForm({...form,ends:e.target.value})}/></label><label>Venue<input required value={form.venue} onChange={(e) => setForm({...form,venue:e.target.value})}/></label><label>Capacity (optional)<input min="1" type="number" value={form.capacity} onChange={(e) => setForm({...form,capacity:e.target.value})}/></label></div><label>Description<textarea required minLength={3} rows={3} value={form.description} onChange={(e) => setForm({...form,description:e.target.value})}/></label><button className="primary-button" disabled={busy}>Save draft</button></form>
    <div className="event-admin-layout"><aside><h2>Events</h2>{events.map((item) => <button className={selected === item.id ? 'active' : ''} key={item.id} onClick={() => setSelected(item.id)}><strong>{item.title}</strong><span>{new Date(item.starts_at).toLocaleDateString()} · {item.status}</span></button>)}</aside><div className="attendance-panel">{selectedEvent ? <><div className="attendance-title"><div><h2>{selectedEvent.title}</h2><p>{selectedEvent.venue} · {new Date(selectedEvent.starts_at).toLocaleString()}</p></div><div className="status-actions">{selectedEvent.status === 'draft' && <button disabled={busy} onClick={() => setStatus(selectedEvent.id,'published')}>Publish</button>}{selectedEvent.status === 'published' && <><button disabled={busy} onClick={() => setStatus(selectedEvent.id,'completed')}>Complete</button><button disabled={busy} onClick={() => setStatus(selectedEvent.id,'cancelled')}>Cancel</button></>}</div></div><div className="attendance-summary"><span><strong>{report.going}</strong> going</span><span><strong>{report.declined}</strong> declined</span><span><strong>{report.attended}</strong> attended</span></div><div className="attendance-list">{members.map((member) => { const row = rows.find((x) => x.member_id === member.id); return <div key={member.id}><span><strong>{member.full_name}</strong><small>{member.membership_number || 'Number pending'} · {row?.response?.replace('_',' ') || 'No response'}</small></span><label><input type="checkbox" checked={Boolean(row?.checked_in_at)} disabled={busy || (!goingIds.has(member.id) && selectedEvent.status === 'draft')} onChange={(e) => checkIn(member.id,e.target.checked)}/> Attended</label></div>; })}</div></> : <div className="event-empty">Create an event to begin.</div>}</div></div>
  </section>;
}
