import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Mail, MapPin, Quote, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { PageHero } from '../components/ui/PageHero';
import type { Executive } from '../types/executive';

export function ExecutiveProfile({ executive }: { executive: Executive }) {
  if (executive.status === 'pending') {
    return <><PageHero eyebrow={executive.role} title={executive.name} text="This executive profile is coming soon." /><section className="section"><a className="back-link" href="#/leadership"><ArrowLeft size={17} />Back to Leadership</a></section></>;
  }
  return <><section className="executive-hero"><a className="back-link light-back" href="#/leadership"><ArrowLeft size={17} />Leadership &amp; Advisory Council</a><div className="executive-hero-grid"><div className="executive-photo"><span>{executive.name.split(' ').map((name) => name[0]).join('').slice(0, 2)}</span><small>Official portrait to be added</small></div><div><span className="eyebrow light">{executive.role}</span><h1>{executive.name}</h1><p className="term">Executive Term 2026–2031</p><div className="profile-meta">{executive.location && <span><MapPin />{executive.location}</span>}{executive.occupation && <span><BriefcaseBusiness />{executive.occupation}</span>}{executive.organisation && <span><ShieldCheck />{executive.organisation}</span>}</div></div></div></section><section className="section profile-layout"><div className="profile-main"><span className="eyebrow">About</span><h2>A commitment to service and community.</h2><p className="profile-bio">{executive.bio}</p>{executive.reason && <div className="profile-block"><Quote /><div><h3>Why I Accepted the Leadership Role</h3><p>{executive.reason}</p></div></div>}{executive.vision && <div className="profile-block"><Sparkles /><div><h3>My Vision for the Association</h3><p>{executive.vision}</p></div></div>}</div><aside className="profile-sidebar">{executive.skills && <div><h3>Areas of Expertise</h3><div className="skill-list">{executive.skills.map((skill) => <span key={skill}><CheckCircle2 />{skill}</span>)}</div></div>}{executive.motto && <div className="motto-card"><Quote /><span>Personal Motto</span><strong>“{executive.motto}”</strong></div>}{(executive.email || executive.facebook) && <div><h3>Connect</h3><div className="contact-links">{executive.email && <a href={`mailto:${executive.email}`}><Mail />Email</a>}{executive.facebook && <a href={executive.facebook} target="_blank" rel="noreferrer"><Users />Facebook</a>}</div></div>}</aside></section></>;
}
