import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { supabase } from '../lib/supabase';
import './Finance.css';

type Period = { id: string; name: string; amount: number; currency: string; due_date: string; is_active: boolean };
type Member = { id: string; full_name: string; membership_number: string | null };
type Payment = { id: string; member_id: string; period_id: string; amount: number; paid_at: string; payment_method: string; reference: string | null; profiles: { full_name: string; membership_number: string | null } | null; dues_periods: { name: string; currency: string } | null };
const money = (amount: number, currency = 'GMD') => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(amount);

export function FinanceAdministration() {
  const [allowed, setAllowed] = useState<boolean | null>(null);
  const [periods, setPeriods] = useState<Period[]>([]); const [members, setMembers] = useState<Member[]>([]); const [payments, setPayments] = useState<Payment[]>([]);
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [search, setSearch] = useState('');
  const [receipt, setReceipt] = useState({ period: '', member: '', amount: '', date: new Date().toISOString().slice(0, 10), method: 'cash', reference: '', note: '' });
  const [period, setPeriod] = useState({ name: '', amount: '', dueDate: '', currency: 'GMD' });
  const load = useCallback(async () => {
    const { data: authorized } = await supabase.rpc('can_manage_finances'); setAllowed(Boolean(authorized)); if (!authorized) return;
    const [p, m, r] = await Promise.all([
      supabase.from('dues_periods').select('*').order('due_date', { ascending: false }),
      supabase.from('profiles').select('id, full_name, membership_number').eq('is_active', true).order('full_name'),
      supabase.from('dues_payments').select('id, member_id, period_id, amount, paid_at, payment_method, reference, profiles!dues_payments_member_id_fkey(full_name, membership_number), dues_periods(name, currency)').order('paid_at', { ascending: false }),
    ]);
    if (p.error || m.error || r.error) setMessage('Financial records could not be loaded.');
    else { setPeriods((p.data ?? []) as Period[]); setMembers((m.data ?? []) as Member[]); setPayments((r.data ?? []) as unknown as Payment[]); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => payments.filter((item) => `${item.profiles?.full_name} ${item.profiles?.membership_number} ${item.reference} ${item.dues_periods?.name}`.toLowerCase().includes(search.toLowerCase())), [payments, search]);
  async function addPeriod(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const { data: auth } = await supabase.auth.getUser(); const { error } = await supabase.from('dues_periods').insert({ name: period.name.trim(), amount: Number(period.amount), currency: period.currency.toUpperCase(), due_date: period.dueDate, created_by: auth.user?.id }); setBusy(false); if (error) setMessage(error.message); else { setPeriod({ name: '', amount: '', dueDate: '', currency: 'GMD' }); setMessage('Dues period published.'); void load(); } }
  async function addPayment(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const { error } = await supabase.rpc('record_dues_payment', { target_period_id: receipt.period, target_member_id: receipt.member, payment_amount: Number(receipt.amount), payment_date: `${receipt.date}T12:00:00Z`, method: receipt.method, payment_reference: receipt.reference, payment_note: receipt.note }); setBusy(false); if (error) setMessage(error.message); else { setReceipt({ ...receipt, amount: '', reference: '', note: '' }); setMessage('Payment recorded and receipt added to the member account.'); void load(); } }
  if (allowed === null) return <section className="finance-state">Checking finance access…</section>;
  if (!allowed) return <section className="finance-state"><div><h1>Access denied</h1><p>Financial management is restricted to authorized finance officers.</p><a href="#/dashboard">Return to dashboard</a></div></section>;
  const total = payments.reduce((sum, item) => sum + Number(item.amount), 0);
  return <section className="finance-page"><header className="finance-header"><div><p className="eyebrow">Executive administration</p><h1>Financial Management</h1><p>Publish dues, record receipts and monitor member contributions.</p></div><a className="secondary-button" href="#/dashboard">Back to dashboard</a></header>
    {message && <p className="finance-message" role="status">{message}</p>}
    <div className="finance-summary"><article><span>Total collected</span><strong>{money(total)}</strong></article><article><span>Payments</span><strong>{payments.length}</strong></article><article><span>Active periods</span><strong>{periods.filter((p) => p.is_active).length}</strong></article></div>
    <div className="finance-forms"><form onSubmit={addPayment}><h2>Record a payment</h2><label>Member<select required value={receipt.member} onChange={(e) => setReceipt({ ...receipt, member: e.target.value })}><option value="">Select member</option>{members.map((m) => <option key={m.id} value={m.id}>{m.full_name} {m.membership_number ? `(${m.membership_number})` : ''}</option>)}</select></label><label>Dues period<select required value={receipt.period} onChange={(e) => { const selected = periods.find((p) => p.id === e.target.value); setReceipt({ ...receipt, period: e.target.value, amount: selected ? String(selected.amount) : receipt.amount }); }}><option value="">Select period</option>{periods.filter((p) => p.is_active).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={receipt.amount} onChange={(e) => setReceipt({ ...receipt, amount: e.target.value })} /></label><label>Payment date<input required type="date" value={receipt.date} onChange={(e) => setReceipt({ ...receipt, date: e.target.value })} /></label></div><label>Payment method<select value={receipt.method} onChange={(e) => setReceipt({ ...receipt, method: e.target.value })}><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="mobile_money">Mobile money</option><option value="other">Other</option></select></label><label>Reference<input value={receipt.reference} onChange={(e) => setReceipt({ ...receipt, reference: e.target.value })} placeholder="Transaction or receipt number" /></label><label>Note<textarea rows={2} value={receipt.note} onChange={(e) => setReceipt({ ...receipt, note: e.target.value })} /></label><button className="primary-button" disabled={busy}>Record payment</button></form>
    <form onSubmit={addPeriod}><h2>Create dues period</h2><label>Period name<input required value={period.name} onChange={(e) => setPeriod({ ...period, name: e.target.value })} placeholder="e.g. 2026 Annual Dues" /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={period.amount} onChange={(e) => setPeriod({ ...period, amount: e.target.value })} /></label><label>Currency<input required maxLength={3} pattern="[A-Za-z]{3}" value={period.currency} onChange={(e) => setPeriod({ ...period, currency: e.target.value })} /></label></div><label>Due date<input required type="date" value={period.dueDate} onChange={(e) => setPeriod({ ...period, dueDate: e.target.value })} /></label><button className="primary-button" disabled={busy}>Publish period</button></form></div>
    <div className="finance-table-heading"><h2>Payment ledger</h2><label>Search receipts<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Member, period or reference" /></label></div><div className="finance-table-wrap"><table><thead><tr><th>Date</th><th>Member</th><th>Period</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td>{new Date(item.paid_at).toLocaleDateString()}</td><td>{item.profiles?.full_name ?? 'Member'}<small>{item.profiles?.membership_number}</small></td><td>{item.dues_periods?.name}</td><td>{item.payment_method.replaceAll('_', ' ')}</td><td>{item.reference || '—'}</td><td>{money(Number(item.amount), item.dues_periods?.currency)}</td></tr>)}</tbody></table>{visible.length === 0 && <p className="finance-empty">No payments match this search.</p>}</div>
  </section>;
}
