import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { supabase } from '../lib/supabase';
import type { ApplicationStatus, Committee, CommitteeMembership, CommitteeRole, VolunteerApplication, VolunteerOpportunity } from '../types/committee';
import './CommitteesVolunteering.css';

const emptyCommittee = { name: '', description: '' };
const emptyOpportunity = { committeeId: '', title: '', description: '', location: '', startsAt: '', endsAt: '', capacity: '' };
export function VolunteerAdministration() {
  const [allowed, setAllowed] = useState<boolean | null>(null); const [committees, setCommittees] = useState<Committee[]>([]); const [opportunities, setOpportunities] = useState<VolunteerOpportunity[]>([]); const [applications, setApplications] = useState<VolunteerApplication[]>([]); const [memberships, setMemberships] = useState<CommitteeMembership[]>([]);
  const [committee, setCommittee] = useState(emptyCommittee); const [opportunity, setOpportunity] = useState(emptyOpportunity); const [assignment, setAssignment] = useState({ committeeId: '', memberId: '', role: 'member' as CommitteeRole }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const { data: authorized } = await supabase.rpc('can_manage_volunteers'); setAllowed(Boolean(authorized)); if (!authorized) return; const [c,o,a,m] = await Promise.all([supabase.from('committees').select('*').order('name'),supabase.from('volunteer_opportunities').select('*, committees(name)').order('starts_at',{ascending:false}),supabase.from('volunteer_applications').select('*, profiles!volunteer_applications_member_id_fkey(full_name, membership_number)').order('created_at',{ascending:false}),supabase.from('committee_memberships').select('*, profiles(full_name, membership_number)').order('joined_at')]); if ([c,o,a,m].some((result)=>result.error)) setMessage('Management records could not be loaded.'); else { setCommittees((c.data??[]) as Committee[]); setOpportunities((o.data??[]) as VolunteerOpportunity[]); setApplications((a.data??[]) as VolunteerApplication[]); setMemberships((m.data??[]) as CommitteeMembership[]); } }, []);
  useEffect(()=>{void load();},[load]);
  async function createCommittee(event: FormEvent) { event.preventDefault(); setBusy(true); const {error}=await supabase.from('committees').insert({name:committee.name.trim(),description:committee.description.trim()}); setMessage(error?error.message:'Committee created.'); if(!error){setCommittee(emptyCommittee);await load();} setBusy(false); }
  async function createOpportunity(event: FormEvent) { event.preventDefault(); setBusy(true); const {data:auth}=await supabase.auth.getUser(); const {error}=await supabase.from('volunteer_opportunities').insert({committee_id:opportunity.committeeId||null,title:opportunity.title.trim(),description:opportunity.description.trim(),location:opportunity.location.trim()||null,starts_at:new Date(opportunity.startsAt).toISOString(),ends_at:new Date(opportunity.endsAt).toISOString(),capacity:opportunity.capacity?Number(opportunity.capacity):null,created_by:auth.user?.id}); setMessage(error?error.message:'Volunteer opportunity created as a draft.'); if(!error){setOpportunity(emptyOpportunity);await load();} setBusy(false); }
  async function assign(event: FormEvent) { event.preventDefault(); setBusy(true); const {error}=await supabase.from('committee_memberships').upsert({committee_id:assignment.committeeId,member_id:assignment.memberId,role:assignment.role},{onConflict:'committee_id,member_id'}); setMessage(error?error.message:'Committee assignment saved.'); if(!error) await load(); setBusy(false); }
  async function opportunityStatus(id:string,status:'open'|'closed'|'completed'){setBusy(true);const {error}=await supabase.rpc('set_volunteer_opportunity_status',{target_opportunity_id:id,new_status:status});setMessage(error?error.message:`Opportunity marked ${status}.`);if(!error)await load();setBusy(false);}
  async function applicationStatus(id:string,status:ApplicationStatus){setBusy(true);const {error}=await supabase.rpc('review_volunteer_application',{target_application_id:id,new_status:status});setMessage(error?error.message:`Application ${status}.`);if(!error)await load();setBusy(false);}
  async function recordHours(id:string){const value=window.prompt('Total hours served');if(value===null)return;setBusy(true);const {error}=await supabase.rpc('record_volunteer_hours',{target_application_id:id,total_hours:Number(value)});setMessage(error?error.message:'Volunteer hours recorded.');if(!error)await load();setBusy(false);}
  if(allowed===null)return <section className="volunteer-state">Checking volunteer management access…</section>; if(!allowed)return <section className="volunteer-state"><div><h1>Access denied</h1><p>Volunteer management is restricted to authorized officers.</p><a href="#/dashboard">Return to dashboard</a></div></section>;
  return <section className="volunteer-page admin"><header className="volunteer-header"><div><p className="eyebrow">Executive administration</p><h1>Committee &amp; Volunteer Management</h1><p>Create teams, recruit volunteers and recognize service.</p></div><a className="secondary-button" href="#/dashboard">Back to dashboard</a></header>{message&&<p className="volunteer-message" role="status">{message}</p>}
    <div className="volunteer-admin-forms"><form onSubmit={createCommittee}><h2>Create committee</h2><label>Name<input required minLength={3} value={committee.name} onChange={e=>setCommittee({...committee,name:e.target.value})}/></label><label>Description<textarea required rows={4} value={committee.description} onChange={e=>setCommittee({...committee,description:e.target.value})}/></label><button className="primary-button" disabled={busy}>Create committee</button></form>
    <form onSubmit={assign}><h2>Assign committee member</h2><label>Committee<select required value={assignment.committeeId} onChange={e=>setAssignment({...assignment,committeeId:e.target.value})}><option value="">Select</option>{committees.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Member ID<input required value={assignment.memberId} onChange={e=>setAssignment({...assignment,memberId:e.target.value})} placeholder="Member UUID"/></label><label>Role<select value={assignment.role} onChange={e=>setAssignment({...assignment,role:e.target.value as CommitteeRole})}><option value="member">Member</option><option value="secretary">Secretary</option><option value="chair">Chair</option></select></label><button className="primary-button" disabled={busy}>Save assignment</button></form></div>
    <form className="opportunity-form" onSubmit={createOpportunity}><h2>Create volunteer opportunity</h2><div><label>Title<input required value={opportunity.title} onChange={e=>setOpportunity({...opportunity,title:e.target.value})}/></label><label>Committee<select value={opportunity.committeeId} onChange={e=>setOpportunity({...opportunity,committeeId:e.target.value})}><option value="">Association-wide</option>{committees.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Starts<input required type="datetime-local" value={opportunity.startsAt} onChange={e=>setOpportunity({...opportunity,startsAt:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={opportunity.endsAt} onChange={e=>setOpportunity({...opportunity,endsAt:e.target.value})}/></label><label>Location<input value={opportunity.location} onChange={e=>setOpportunity({...opportunity,location:e.target.value})}/></label><label>Capacity<input min="1" type="number" value={opportunity.capacity} onChange={e=>setOpportunity({...opportunity,capacity:e.target.value})}/></label></div><label>Description<textarea required rows={3} value={opportunity.description} onChange={e=>setOpportunity({...opportunity,description:e.target.value})}/></label><button className="primary-button" disabled={busy}>Save draft</button></form>
    <h2>Opportunities</h2><div className="admin-records">{opportunities.map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{item.status} · {item.committees?.name??'Association-wide'}</span></div><div>{item.status==='draft'&&<button onClick={()=>opportunityStatus(item.id,'open')}>Open recruitment</button>}{item.status==='open'&&<button onClick={()=>opportunityStatus(item.id,'closed')}>Close</button>}{item.status==='closed'&&<button onClick={()=>opportunityStatus(item.id,'completed')}>Complete</button>}</div></article>)}</div>
    <h2>Volunteer applications</h2><div className="admin-records">{applications.map(item=><article key={item.id}><div><strong>{item.profiles?.full_name??'Member'}</strong><span>{item.status} · {item.hours_served} hours</span></div><div>{item.status==='pending'&&<><button onClick={()=>applicationStatus(item.id,'approved')}>Approve</button><button onClick={()=>applicationStatus(item.id,'declined')}>Decline</button></>} {item.status==='approved'&&<button onClick={()=>recordHours(item.id)}>Record hours</button>}</div></article>)}</div>
    <h2>Committee roster</h2><div className="admin-records">{memberships.map(item=><article key={item.id}><div><strong>{item.profiles?.full_name??item.member_id}</strong><span>{committees.find(c=>c.id===item.committee_id)?.name} · {item.role}</span></div></article>)}</div>
  </section>;
}
