import {
  ArrowLeft, ArrowRight, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2,
  GraduationCap, HandHeart, HeartHandshake, History, Leaf, Mail, MapPin,
  Menu, Network, Quote, ShieldCheck, Sparkles, Users, X
} from 'lucide-react';
import { useEffect, useState } from 'react';

type Executive = {
  slug: string;
  name: string;
  role: string;
  location?: string;
  occupation?: string;
  organisation?: string;
  bio?: string;
  reason?: string;
  vision?: string;
  motto?: string;
  skills?: string[];
  email?: string;
  facebook?: string;
  status: 'complete' | 'pending';
};

const executives: Executive[] = [
  {
    slug:'omar-bah', name:'Omar Bah', role:'Chairman', location:'The Gambia', occupation:'Relationship Manager', organisation:'AGIB Bank Ltd',
    bio:'Omar Bah is the Chairman of the SANGAJOR B.C.S Class of 2008 Association. A native of Foni in the West Coast Region of The Gambia and a proud alumnus of SANGAJOR Basic Cycle School Class of 2008, Omar has built a distinguished career spanning banking, education, community leadership and youth development. He currently serves as a Relationship Manager at AGIB Bank Ltd, where he works in Retail and Corporate Banking and contributes as a member of both the Deposit Mobilization Committee and the Product Development Committee. Before joining AGIB Bank Ltd, Omar served as a teacher at several institutions and later worked as a Relationship Manager at Vista Bank Gambia. While studying at the University of The Gambia, he served as President of the Foni Students Association, demonstrating a strong commitment to leadership, service and youth empowerment.',
    reason:'I accepted this leadership role because I believe in the strength of unity, responsible leadership and service. Our shared history gives us a strong foundation, and I want to help transform that bond into meaningful opportunities for our members, our former school and the wider community.',
    vision:'My vision is to build a united, transparent and forward-looking Association that supports its members, promotes education and youth development, creates sustainable partnerships and leaves a lasting legacy for future generations.',
    motto:'Leadership Is Service.',
    skills:['Relationship Management','Retail Banking','Corporate Banking','Business Development','Product Development','Community Leadership','Youth Empowerment','Strategic Partnerships','Public Speaking','Team Leadership'],
    status:'complete'
  },
  {
    slug:'kaddy-bojang', name:'Kaddy Bojang', role:'Vice Chairperson', location:'Kanilai, The Gambia', occupation:'Homemaker',
    bio:'Kaddy Bojang serves as Vice Chairperson of the SANGAJOR B.C.S Class of 2008 Association. Based in Kanilai, she is a dedicated homemaker who values service, unity and responsible leadership. She is committed to supporting the Chairperson, strengthening cooperation among members and contributing to initiatives that benefit the Association, its members and the wider community.',
    reason:'I accepted this leadership role because I believe in serving others and contributing to the growth of our Association. I want to support the leadership team, promote unity and help ensure that members feel heard, valued and involved.',
    vision:'My vision is to see a united, organised and supportive Association that works together to achieve its goals, assists its members and gives back to our former school and community.',
    motto:'Leadership Through Service.', email:'fa2bb27@gmail.com', status:'complete'
  },
  {
    slug:'landing-bojang', name:'Landing Bojang', role:'Secretary General', location:'Kanfenda / Sanchaba Sulay Jobe, The Gambia', occupation:'Civil Servant', organisation:'The Gambia Police Force',
    bio:'Landing Bojang serves as Secretary General of the SANGAJOR B.C.S Class of 2008 Association. Born in Foni, he is a proud alumnus of SANGAJOR Basic Cycle School and an Economics graduate of the University of The Gambia. He brings experience in project management, organisational leadership, finance and education. Landing also serves as Assistant Auditor General of the Pan African Students Association and as a tutor in the Economics and Finance Department at the University of The Gambia. His service includes voluntary teaching and more than five years as Secretary General of his village football club.',
    reason:'I accepted this leadership role because I want to serve my school and community. Through dedication, teamwork and responsible leadership, we can build a stronger Association that positively impacts our members and future generations.',
    vision:'My vision is to help the Association achieve its stated goals by working closely with members to promote unity, progress and sustainable community development. I look forward to contributing to initiatives that create lasting opportunities for our community.',
    motto:'Nothing Good Comes Easy.', skills:['Project Management','Finance','Accounting','Business','Entrepreneurship'], email:'landingbojang37@gmail.com', status:'complete'
  },
  {
    slug:'lamin-bangura', name:'Lamin Bangura', role:'Assistant Secretary General', location:'Brikama, The Gambia', occupation:'Police Officer', organisation:'The Gambia Police Force',
    bio:'Lamin Bangura serves as Assistant Secretary General of the SANGAJOR B.C.S Class of 2008 Association. He is a Police Officer and Police Prosecutor with The Gambia Police Force and is currently pursuing a Bachelor of Laws degree. Dedicated to service, discipline and justice, he is passionate about contributing to the Association through effective administration, teamwork and community engagement. He is committed to supporting initiatives that empower members and create positive opportunities for future generations.',
    reason:'I accepted this leadership role because I want to help build a better future for the younger generation. By working together, we can create opportunities, strengthen our Association and make a positive contribution to our community.',
    vision:'My vision is to see the Association continue to grow through progress, unity and sustainable development. I hope to contribute to building a stronger and more organised Association that positively impacts its members and the wider community.',
    motto:'Together We Achieve More.', skills:['Leadership','Communication','Community Development','Writing','Project Management'], email:'banguralamin13@gmail.com', status:'complete'
  },
  {
    slug:'mbaye-manga', name:'Mbaye Manga', role:'Treasurer', location:'Banjul, The Gambia', occupation:'Civil Servant', organisation:'The Gambia Police Force',
    bio:'Mbaye Manga serves as Treasurer of the SANGAJOR B.C.S Class of 2008 Association. An alumnus of SANGAJOR Basic Cycle School’s Grade 9 Class of 2008, he is a dedicated civil servant with a strong background in administrative leadership, training coordination and policy planning. Passionate about public service, teamwork and accountability, he believes that sound financial management is essential to building a strong and sustainable Association.',
    reason:'I accepted this leadership role out of a strong desire to serve our batch and give back to the school community that helped shape who we are today. Being entrusted with our shared resources is both an honour and a responsibility.',
    vision:'My vision is to build a financially strong and trustworthy Association that reliably supports its members and our former school. I will promote accurate records, contribution compliance and regular transparent reporting while ensuring our resources are managed responsibly.',
    motto:'The After Party — Service Before Enjoyment.', skills:['Leadership','Community Development','Technology','Education','Administrative Leadership'], email:'zagnam19@gmail.com', facebook:'https://www.facebook.com/mangaz.172', status:'complete'
  },
  {
    slug:'bakary-bojang', name:'Bakary Bojang', role:'Assistant Treasurer', location:'Brikama, The Gambia', occupation:'Civil Servant', organisation:'Ministry of Basic and Secondary Education (MoBSE)',
    bio:'Bakary Bojang serves as Assistant Treasurer of the SANGAJOR B.C.S Class of 2008 Association. He is a civil servant with the Ministry of Basic and Secondary Education and is committed to supporting the Association through responsible financial stewardship, communication and teamwork.',
    reason:'I accepted this leadership role to give back to my alma mater—the school that helped shape who I am today. Serving as Assistant Treasurer allows me to contribute to the growth of the Association and support initiatives that benefit our members and community.',
    vision:'My vision is to work effectively with members to achieve our shared aims and objectives while strengthening unity, cooperation and collective responsibility.',
    motto:'Power to the People.', skills:['Communication'], email:'bakabojang87@gmail.com', status:'complete'
  },
  {
    slug:'saidou-jallow', name:'Saidou Jallow', role:'Auditor General',
    bio:'Saidou Jallow serves as Auditor General of the SANGAJOR B.C.S Class of 2008 Association. In this role, he supports transparency, accountability and responsible financial management by helping review the Association’s records, procedures and financial activities. He is committed to safeguarding the trust of members and strengthening the systems that support the Association’s long-term growth.',
    reason:'I accepted this leadership role to support accountability, transparency and responsible management within the Association. I believe strong internal controls and accurate reporting are essential to earning and maintaining the trust of our members.',
    vision:'My vision is to help build an Association known for integrity, proper record-keeping and responsible use of its resources, ensuring that every activity supports the interests of members and the wider community.',
    motto:'Integrity Builds Trust.', skills:['Accountability','Financial Review','Transparency','Record-Keeping','Teamwork'], status:'complete'
  },
  {
    slug:'fatou-nyassi', name:'Fatou Nyassi', role:'Assistant Auditor General', location:'Kafuta, The Gambia', occupation:'Homemaker and Businesswoman',
    bio:'Fatou Nyassi serves as Assistant Auditor General of the SANGAJOR B.C.S Class of 2008 Association. A former Head Girl of SANGAJOR Basic Cycle School, she brings valuable leadership experience, confidence and a strong sense of responsibility to her position. As a homemaker and businesswoman, Fatou understands the importance of careful management, accountability and sound decision-making. She supports the review of the Association’s financial activities to promote transparency and proper record-keeping. Passionate about unity and community development, she is committed to contributing her time, business knowledge and ideas towards building a strong, responsible and successful Association.',
    reason:'I accepted this leadership role because I value honesty, transparency and accountability. As a former Head Girl and businesswoman, I believe my leadership experience and attention to detail will help me support the responsible management of the Association’s finances and contribute meaningfully to its continued growth.',
    vision:'My vision is to see the Association become a united, transparent and financially responsible organisation that supports its members, creates meaningful opportunities and makes a lasting positive impact within the school and wider community.',
    motto:'Unity Is Strength.', skills:['Leadership','Communication','Public Relations','Business','Community Development','Entrepreneurship','Fundraising'], email:'nyassif469@gmail.com', status:'complete'
  },
  {
    slug:'banna-bojang', name:'Banna Bojang', role:'Information & Public Relations Officer (IPRO)', occupation:'Chef | Founder, Elegant Empire AI Studio',
    bio:'Banna Bojang serves as the Information & Public Relations Officer of the SANGAJOR B.C.S Class of 2008 Association. She is a chef and the Founder of Elegant Empire AI Studio. Passionate about communication, technology, creative storytelling and community service, she is leading the development of the Association’s official digital platform. Through her role, she is committed to strengthening transparency, preserving the Association’s legacy and ensuring that members remain informed, represented and actively engaged.',
    reason:'I accepted this leadership role because I believe communication is essential to unity, trust and progress. I want to serve my community by helping members stay informed, promoting transparency and documenting the Association’s journey for future generations.',
    vision:'My vision is to build a strong and reliable communication system that connects members, promotes participation and preserves the history of the Class of 2008. I hope to strengthen the Association’s public image and use digital tools to support its long-term growth.',
    motto:'There Is No Problem That Cannot Be Solved Through Communication.', skills:['Communication','Public Relations','Media','Technology','Writing','Graphic Design'], status:'complete'
  },
  {
    slug:'tida-bojang', name:'Tida Bojang', role:'Assistant Information & Public Relations Officer', location:'Brikama, The Gambia', occupation:'Student and Civil Servant', organisation:'Ministry of Agriculture — Department of Soil and Water Management',
    bio:'Tida Bojang serves as Assistant Information & Public Relations Officer of the SANGAJOR B.C.S Class of 2008 Association. A proud graduate of SANGAJOR Basic Cycle School, she is currently studying Agriculture at The Gambia College while serving with the Ministry of Agriculture under the Department of Soil and Water Management. Passionate about communication, community engagement and sustainable development, Tida is committed to strengthening the Association’s public image, encouraging active member participation and promoting initiatives that benefit both the Association and the wider community.',
    reason:'I accepted this leadership role because I enjoy connecting with people and sharing information effectively. As Assistant IPRO, I want to support the Association’s communication efforts, promote its achievements, encourage active member participation and help build a positive and trusted public image.',
    vision:'My vision is to see the Association grow into a larger and more impactful organisation that reaches more people while giving back to our former school and the wider community. Through effective communication and teamwork, I hope to help strengthen our Association and inspire meaningful community development.',
    motto:'Together We Can Achieve More — Two Heads Are Better Than One.', skills:['Communication','Public Relations','Community Development'], email:'bojangtidam9@gmail.com', status:'complete'
  },
  {
    slug:'demba-jammeh', name:'Demba Jammeh', role:'Programme Officer', location:'Brikama Town, The Gambia', occupation:'Civil Servant', organisation:'The Gambia National Petroleum Corporation (GNPC)',
    bio:'Demba Jammeh serves as Programme Officer of the SANGAJOR B.C.S Class of 2008 Association. Born and raised in Sangajor, Foni Kansala, he is a dedicated civil servant with a strong passion for public service and community development. He works with The Gambia National Petroleum Corporation and is currently pursuing the ACCA qualification. His upbringing instilled in him a deep sense of civic responsibility and a desire to give back.',
    reason:'I accepted this leadership role because I am passionate about empowering people and helping others reach their full potential. I enjoy building cohesive teams, recognising individual strengths and supporting members to achieve shared goals.',
    vision:'My vision is to build an Association that acts as a catalyst for meaningful grassroots development. I want every voice to be valued while we strengthen outreach, grow membership and deliver impactful community projects.',
    motto:'Together We Achieve More.', skills:['Leadership','Communication','Public Relations','Finance','Accounting','Community Development','Entrepreneurship','Event Planning','Education','Fundraising','Project Management'], email:'djammeh964@gmail.com', status:'complete'
  },
  {
    slug:'bakary-colley', name:'Bakary Colley', role:'Assistant Programme Officer', location:'Farafenni, The Gambia', occupation:'Civil Servant', organisation:'The Gambia Armed Forces',
    bio:'Bakary Colley serves as Assistant Programme Officer of the SANGAJOR B.C.S Class of 2008 Association. Originally from Burrock in Foni Kansala District, he is a dedicated civil servant who is passionate about service and community development. He is committed to supporting the planning and implementation of programmes that benefit members and the wider community.',
    reason:'I accepted this role because I want to be part of a team that turns ideas into action. I enjoy supporting programmes from planning through implementation, ensuring that goals are achieved, reports are accurate and beneficiaries are served well.',
    vision:'My vision is to support programmes that are well planned, well delivered and truly improve lives. I want every activity to lead to measurable impact and accountability.',
    motto:'Unity Is Strength.', email:'colleyb949@gmail.com', status:'complete'
  },
  {
    slug:'ismaila-manga', name:'Ismaila Manga', role:'Adviser', location:'Milan, Italy', occupation:'Civil Servant', organisation:'University',
    bio:'Ismaila Manga serves as an Adviser of the SANGAJOR B.C.S Class of 2008 Association. Originally from Kanfenda, he is a former student of SANGAJOR Basic Cycle School and Fatima Senior Secondary School and currently resides in Milan, Italy. He enjoys football, athletics, reading and listening to music. As an adviser, he is committed to supporting the Association through teamwork, guidance and community-focused initiatives.',
    reason:'I accepted this leadership role because I believe that giving back to my alma mater and serving the community is a meaningful responsibility.',
    vision:'My vision is to see our Association become a source of positive change by discouraging drug abuse among young people, encouraging students to take education seriously and promoting practical skills for successful and responsible lives.',
    motto:'There’s Water Under the Bridge.', email:'mangaismaila29@gmail.com', status:'complete'
  },
  {
    slug:'yusupha-badjie', name:'Yusupha Badjie', role:'Adviser',
    bio:'Yusupha Badjie serves as an Adviser of the SANGAJOR B.C.S Class of 2008 Association. He supports the executive team by offering guidance, encouraging sound decision-making and helping the Association remain focused on unity, service and sustainable progress. He is committed to contributing his experience and perspective to initiatives that strengthen members and benefit the wider community.',
    reason:'I accepted this role because I believe the Association can achieve more when members share their experience, listen to one another and work together with a common purpose.',
    vision:'My vision is to see a united and well-organised Association that makes thoughtful decisions, supports its members and delivers meaningful initiatives for our former school and community.',
    motto:'Unity, Wisdom and Service.', skills:['Advisory Support','Leadership','Teamwork','Community Development','Strategic Guidance'], status:'complete'
  },
  { slug:'mariama-sibo-bojang', name:'Mariama Sibo Bojang', role:'Adviser', status:'pending' },
  { slug:'mr-bojang', name:'Mr. Bojang', role:'Patron Adviser (Former Teacher)', status:'pending' }
];

const impactAreas = [
  { icon: GraduationCap, title: 'Education', text: 'Supporting learning opportunities and educational initiatives at SANGAJOR B.C.S and beyond.' },
  { icon: HandHeart, title: 'Community Service', text: 'Organising meaningful service that benefits our school, community and environment.' },
  { icon: HeartHandshake, title: 'Member Welfare', text: 'Building mutual support systems for members and their families in times of need.' },
  { icon: Users, title: 'Youth Mentorship', text: 'Guiding young people through education, leadership and positive role models.' },
  { icon: ShieldCheck, title: 'Partnerships', text: 'Working with organisations and supporters who share our values and ambitions.' },
  { icon: Leaf, title: 'Sustainable Development', text: 'Creating long-term programmes that can serve future generations.' }
];
const reasonsToJoin = [
  { icon: Network, title: 'Reconnect', text: 'Strengthen friendships and professional connections formed during our school years.' },
  { icon: HandHeart, title: 'Contribute', text: 'Use your experience, ideas and skills to support members, our school and the wider community.' },
  { icon: History, title: 'Preserve Our Legacy', text: 'Help document the memories, milestones and achievements of the Class of 2008.' }
];
const navItems = [['Home','#/'],['About','#/about'],['Leadership','#/leadership'],['Membership','#/membership'],['Focus Areas','#/focus'],['Updates','#/updates'],['Our Journey','#/journey'],['Contact','#/contact']];

function useRoute(){const read=()=>window.location.hash.replace('#','')||'/';const[route,setRoute]=useState(read);useEffect(()=>{const handler=()=>{setRoute(read());window.scrollTo({top:0,behavior:'smooth'});};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);return route;}
function Header(){const[menuOpen,setMenuOpen]=useState(false);return <header className="site-header"><a className="brand" href="#/"><div className="brand-mark">S</div><div><strong>SANGAJOR</strong><span>B.C.S Class of 2008 Association</span></div></a><nav className="desktop-nav">{navItems.map(([label,href])=><a key={href} href={href}>{label}</a>)}</nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button>{menuOpen&&<nav className="mobile-nav">{navItems.map(([label,href])=><a key={href} href={href} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav>}</header>}
function Footer(){return <footer><div className="footer-grid"><div><div className="brand footer-brand"><div className="brand-mark">S</div><div><strong>SANGAJOR</strong><span>B.C.S Class of 2008 Association</span></div></div><p>Together since childhood. United for life.</p></div><div><h3>Explore</h3><a href="#/about">Our Story</a><a href="#/focus">Focus Areas</a><a href="#/journey">Our Journey</a></div><div><h3>Connect</h3><a href="mailto:info@sangajor08.org">info@sangajor08.org</a><span>The Gambia and beyond</span></div></div><div className="footer-bottom"><span>© 2026 SANGAJOR B.C.S Class of 2008 Association.</span><span>Designed & developed by Elegant Empire AI Studio.</span></div></footer>}
function PageHero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>}
function CTA(){return <section className="cta-section"><div><span className="eyebrow light">Get Involved</span><h2>Every great legacy begins with people who choose to act.</h2><p>Join us as we build a stronger future for our members, our school and our community.</p></div></section>}
function Home(){return <><section className="hero"><div className="hero-content"><span className="eyebrow">The official digital platform of the Class of 2008</span><h1>Together since childhood. <em>United for life.</em></h1><p>What began in one classroom is becoming a lifelong commitment to support one another, serve our school and strengthen our community.</p><div className="hero-actions"><a className="button" href="#/leadership">Meet Our Leadership <ArrowRight size={18}/></a><a className="button button-secondary" href="#/about">Learn Our Story</a></div></div></section><section className="section"><div className="section-heading centered"><span className="eyebrow">Our Focus Areas</span><h2>Six ways we plan to create lasting value.</h2></div><div className="card-grid">{impactAreas.map(({icon:Icon,title,text})=><article className="impact-card" key={title}><div className="icon-wrap"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section muted-section leadership-preview"><div className="section-heading"><span className="eyebrow">Leadership</span><h2>Meet the people serving our shared mission.</h2><a className="text-link" href="#/leadership">Explore leadership <ArrowRight size={17}/></a></div><div className="mini-leaders">{executives.filter(e=>e.status==='complete').slice(0,4).map(e=><a href={`#/leadership/${e.slug}`} key={e.slug}><span>{e.name.split(' ').map(n=>n[0]).join('')}</span><div><strong>{e.name}</strong><small>{e.role}</small></div></a>)}</div></section><CTA/></>}
function About(){return <><PageHero eyebrow="About SANGAJOR" title="A shared past. A purposeful future." text="The Class of 2008 is transforming lifelong connections into an organised association committed to service, education and community development."/><section className="section"><div className="story-grid"><div><span className="eyebrow">Our Story</span><h2>From Primary 1 through Grade 9.</h2><p>Members learned, grew and completed their basic education together at SANGAJOR Basic Cycle School. In 2026, members began formalising that bond through elected leadership, a ratified constitution and preparations for NGO registration.</p></div><blockquote>We are starting from unity, honesty and a clear commitment to serve.</blockquote></div></section></>}
function Leadership(){const complete=executives.filter(e=>e.status==='complete').length;return <><PageHero eyebrow="Leadership & Advisory Council" title="Serving with integrity, experience and shared responsibility." text="Meet the elected officers and advisers helping guide the Association."/><section className="section"><div className="leadership-summary"><div><span className="eyebrow">Executive Term</span><h2>2026–2031</h2></div><div className="profile-progress"><strong>{complete} of {executives.length}</strong><span>profiles completed</span><div><i style={{width:`${(complete/executives.length)*100}%`}}/></div></div></div><div className="leadership-grid">{executives.map(e=><article className={`leader-card ${e.status}`} key={e.slug}><div className="leader-portrait"><span>{e.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span>{e.status==='pending'&&<small>Profile Coming Soon</small>}</div><div className="leader-card-body"><span>{e.role}</span><h3>{e.name}</h3>{e.location&&<p><MapPin size={15}/>{e.location}</p>}{e.occupation&&<p><BriefcaseBusiness size={15}/>{e.occupation}</p>}{e.status==='complete'?<a className="profile-link" href={`#/leadership/${e.slug}`}>View Profile <ArrowRight size={16}/></a>:<div className="pending-label">Profile Coming Soon</div>}</div></article>)}</div></section></>}
function ExecutiveProfile({executive}:{executive:Executive}){if(executive.status==='pending')return <><PageHero eyebrow={executive.role} title={executive.name} text="This executive profile is coming soon."/><section className="section"><a className="back-link" href="#/leadership"><ArrowLeft size={17}/>Back to Leadership</a></section></>;return <><section className="executive-hero"><a className="back-link light-back" href="#/leadership"><ArrowLeft size={17}/>Leadership & Advisory Council</a><div className="executive-hero-grid"><div className="executive-photo"><span>{executive.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><small>Official portrait to be added</small></div><div><span className="eyebrow light">{executive.role}</span><h1>{executive.name}</h1><p className="term">Executive Term 2026–2031</p><div className="profile-meta">{executive.location&&<span><MapPin/>{executive.location}</span>}{executive.occupation&&<span><BriefcaseBusiness/>{executive.occupation}</span>}{executive.organisation&&<span><ShieldCheck/>{executive.organisation}</span>}</div></div></div></section><section className="section profile-layout"><div className="profile-main"><span className="eyebrow">About</span><h2>A commitment to service and community.</h2><p className="profile-bio">{executive.bio}</p>{executive.reason&&<div className="profile-block"><Quote/><div><h3>Why I Accepted the Leadership Role</h3><p>{executive.reason}</p></div></div>}{executive.vision&&<div className="profile-block"><Sparkles/><div><h3>My Vision for the Association</h3><p>{executive.vision}</p></div></div>}</div><aside className="profile-sidebar">{executive.skills&&<div><h3>Areas of Expertise</h3><div className="skill-list">{executive.skills.map(s=><span key={s}><CheckCircle2/>{s}</span>)}</div></div>}{executive.motto&&<div className="motto-card"><Quote/><span>Personal Motto</span><strong>“{executive.motto}”</strong></div>}{(executive.email||executive.facebook)&&<div><h3>Connect</h3><div className="contact-links">{executive.email&&<a href={`mailto:${executive.email}`}><Mail/>Email</a>}{executive.facebook&&<a href={executive.facebook} target="_blank" rel="noreferrer"><Users/>Facebook</a>}</div></div>}</aside></section></>}
function Membership(){return <><PageHero eyebrow="Membership" title="Belong to the community you helped create." text="Membership reconnects classmates, strengthens mutual support and gives every member a voice."/><section className="section"><div className="card-grid">{reasonsToJoin.map(({icon:Icon,title,text})=><article className="impact-card" key={title}><div className="icon-wrap"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section></>}
function Focus(){return <><PageHero eyebrow="Our Focus Areas" title="Plans designed to create lasting value." text="These areas describe what we intend to build, support and improve over time."/><section className="section"><div className="card-grid">{impactAreas.map(({icon:Icon,title,text})=><article className="impact-card" key={title}><div className="icon-wrap"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section></>}
function Updates(){return <><PageHero eyebrow="News & Announcements" title="Official updates in one trusted place." text="A clear public record of approved announcements and Association developments."/><section className="section"><div className="update-grid"><article><CalendarDays/><span>Development</span><h3>Project Legacy public platform</h3><p>The website foundation and leadership directory are now being implemented.</p></article><article><BookOpen/><span>Leadership</span><h3>Executive profiles being published</h3><p>Completed profiles are live while remaining members submit their information.</p></article></div></section></>}
function Journey(){return <><PageHero eyebrow="Our Journey" title="A shared history. A growing legacy." text="This living timeline will expand with photographs, memories, milestones and future service."/><section className="section journey-section"><div className="timeline"><div><span>Before 2008</span><h3>Growing and learning together</h3></div><div><span>2008</span><h3>Class journey completed</h3></div><div><span>2026</span><h3>Association formally establishing</h3></div><div><span>Next</span><h3>Service, impact and legacy</h3></div></div></section></>}
function Contact(){return <><PageHero eyebrow="Contact" title="Connect with SANGAJOR." text="Questions about membership, partnerships or the Association can be directed through the official channels below."/><section className="section"><div className="contact-grid"><article><Mail/><h3>Email</h3><a href="mailto:info@sangajor08.org">info@sangajor08.org</a></article><article><MapPin/><h3>Community</h3><p>The Gambia and members around the world.</p></article><article><Users/><h3>Membership</h3><a href="https://forms.gle/xdcesGiV6nWmDwPs7" target="_blank" rel="noreferrer">Open registration form</a></article></div></section></>}

export default function App(){const route=useRoute();const profileMatch=route.match(/^\/leadership\/([^/]+)$/);let page;if(profileMatch){const executive=executives.find(e=>e.slug===profileMatch[1]);page=executive?<ExecutiveProfile executive={executive}/>:<Leadership/>;}else{const pages:Record<string,JSX.Element>={'/':<Home/>,'/about':<About/>,'/leadership':<Leadership/>,'/membership':<Membership/>,'/focus':<Focus/>,'/updates':<Updates/>,'/journey':<Journey/>,'/contact':<Contact/>};page=pages[route]??<Home/>;}return <div className="site-shell"><Header/><main id="top">{page}</main><Footer/></div>}
