-- Expand the existing Lesson 1 record without replacing it or member progress.
alter table public.lesson_progress drop constraint if exists lesson_progress_check;
alter table public.lesson_progress add constraint lesson_progress_valid_completion check (completed_at is null or (lesson_slug like 'digital-income-lesson-%' and knowledge_submitted and knowledge_score >= 70));
drop policy if exists "Members manage their own incomplete lesson progress" on public.lesson_progress;
create policy "Members manage their own lesson progress" on public.lesson_progress for all to authenticated using (auth.uid()=member_id) with check (auth.uid()=member_id);

create table public.course_enrolments (
 id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
 course_slug text not null, enrolled_at timestamptz not null default now(), completed_at timestamptz,
 unique(member_id,course_slug)
);
create table public.course_assessments (
 id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
 course_slug text not null, answers jsonb not null default '{}' check(jsonb_typeof(answers)='object'), score integer not null check(score between 0 and 100), submitted_at timestamptz not null default now(), unique(member_id,course_slug)
);
create table public.course_assignments (
 id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
 course_slug text not null, submission_text text not null check(char_length(trim(submission_text)) between 200 and 10000),
 status text not null default 'submitted' check(status in ('submitted','changes_requested','approved')), submitted_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references public.profiles(id), reviewer_feedback text, unique(member_id,course_slug),
 check(status <> 'approved' or (reviewed_at is not null and reviewed_by is not null))
);
create table public.learning_certificates (
 id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id) on delete cascade,
 course_slug text not null, status text not null default 'approved' check(status='approved'), approved_by uuid not null references public.profiles(id), approved_at timestamptz not null default now(), certificate_number text not null unique default ('SA-DI-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))), unique(member_id,course_slug)
);

alter table public.course_enrolments enable row level security; alter table public.course_assessments enable row level security; alter table public.course_assignments enable row level security; alter table public.learning_certificates enable row level security;
create policy "Members manage own enrolment" on public.course_enrolments for all to authenticated using(auth.uid()=member_id) with check(auth.uid()=member_id);
create policy "Members view own assessment" on public.course_assessments for select to authenticated using(auth.uid()=member_id);
create policy "Members view own assignment" on public.course_assignments for select to authenticated using(auth.uid()=member_id);
create policy "Members submit own assignment" on public.course_assignments for insert to authenticated with check(auth.uid()=member_id and status='submitted' and reviewed_by is null);
create policy "Members revise own unapproved assignment" on public.course_assignments for update to authenticated using(auth.uid()=member_id and status<>'approved') with check(auth.uid()=member_id and status='submitted' and reviewed_by is null and reviewed_at is null);
create policy "Members view own certificate" on public.learning_certificates for select to authenticated using(auth.uid()=member_id);
create policy "Reviewers view assignments" on public.course_assignments for select to authenticated using(public.is_executive(auth.uid()) or exists(select 1 from public.member_teacher_network t where t.member_id=auth.uid() and t.status='approved'));
create policy "Reviewers review assignments" on public.course_assignments for update to authenticated using(public.is_executive(auth.uid()) or exists(select 1 from public.member_teacher_network t where t.member_id=auth.uid() and t.status='approved')) with check(public.is_executive(auth.uid()) or exists(select 1 from public.member_teacher_network t where t.member_id=auth.uid() and t.status='approved'));

create or replace function public.digital_income_correct_answers(n integer) returns jsonb language sql immutable as $$ select case n when 2 then '{"q1":"1","q2":"1","q3":"0","q4":"1","q5":"0","q6":"1"}' when 3 then '{"q1":"0","q2":"0","q3":"1","q4":"2","q5":"1","q6":"0"}' when 4 then '{"q1":"1","q2":"0","q3":"1","q4":"1","q5":"0","q6":"2"}' when 5 then '{"q1":"1","q2":"0","q3":"1","q4":"1","q5":"0","q6":"0"}' when 6 then '{"q1":"0","q2":"0","q3":"2","q4":"1","q5":"0","q6":"1"}' end $$;
create or replace function public.submit_digital_income_knowledge_check(lesson_number integer,submitted_answers jsonb) returns integer language plpgsql security definer set search_path=public as $$declare correct jsonb; result integer;begin if auth.uid() is null or lesson_number not between 2 and 6 then raise exception 'Invalid lesson';end if;if not exists(select 1 from lesson_progress where member_id=auth.uid() and lesson_slug='digital-income-lesson-'||(lesson_number-1) and completed_at is not null) then raise exception 'Previous lesson must be completed';end if;correct:=digital_income_correct_answers(lesson_number);select round(100.0*count(*) filter(where submitted_answers->>key=value)/6) into result from jsonb_each_text(correct);insert into lesson_progress(member_id,lesson_slug,knowledge_answers,knowledge_score,knowledge_submitted) values(auth.uid(),'digital-income-lesson-'||lesson_number,submitted_answers,result,true) on conflict(member_id,lesson_slug) do update set knowledge_answers=excluded.knowledge_answers,knowledge_score=excluded.knowledge_score,knowledge_submitted=true,updated_at=now();return result;end$$;
create or replace function public.complete_digital_income_lesson(lesson_number integer,section_ids jsonb,activity_response text) returns void language plpgsql security definer set search_path=public as $$declare required text[];begin if lesson_number not between 2 and 6 then raise exception 'Invalid lesson';end if;if not exists(select 1 from lesson_progress where member_id=auth.uid() and lesson_slug='digital-income-lesson-'||(lesson_number-1) and completed_at is not null) then raise exception 'Previous lesson must be completed';end if;required:=case lesson_number when 2 then array['inventory','demand','focus','validate'] when 3 then array['message','portfolio','trust','privacy'] when 4 then array['channels','verify','proposal','warning'] when 5 then array['price','scope','communicate','quality'] else array['method','records','security','scams'] end;if not(select bool_and(section_ids ? x) from unnest(required)x) or char_length(trim(activity_response))<40 then raise exception 'Read every section and complete the activity';end if;update lesson_progress set read_sections=section_ids,pathway_answers=jsonb_build_object('assignment',activity_response),completed_at=now(),updated_at=now() where member_id=auth.uid() and lesson_slug='digital-income-lesson-'||lesson_number and knowledge_submitted and knowledge_score>=70;if not found then raise exception 'A verified score of at least 70 percent is required';end if;end$$;
create or replace function public.submit_digital_income_final_assessment(submitted_answers jsonb) returns integer language plpgsql security definer set search_path=public as $$declare correct constant jsonb:='{"f1":"0","f2":"1","f3":"0","f4":"0","f5":"0","f6":"1"}';result integer;begin if (select count(*) from lesson_progress where member_id=auth.uid() and lesson_slug like 'digital-income-lesson-%' and completed_at is not null)<>6 then raise exception 'Complete all lessons first';end if;select round(100.0*count(*) filter(where submitted_answers->>key=value)/6) into result from jsonb_each_text(correct);insert into course_assessments(member_id,course_slug,answers,score)values(auth.uid(),'digital-income-online-work',submitted_answers,result)on conflict(member_id,course_slug)do update set answers=excluded.answers,score=excluded.score,submitted_at=now();return result;end$$;

create or replace function public.approve_digital_income_assignment(assignment_id uuid,feedback text default null) returns void language plpgsql security definer set search_path=public as $$declare learner uuid;begin if not(public.is_executive(auth.uid()) or exists(select 1 from member_teacher_network where member_id=auth.uid() and status='approved'))then raise exception 'Reviewer access required';end if;update course_assignments set status='approved',reviewed_at=now(),reviewed_by=auth.uid(),reviewer_feedback=feedback where id=assignment_id and course_slug='digital-income-online-work' returning member_id into learner;if learner is null then raise exception 'Assignment not found';end if;if not exists(select 1 from course_assessments where member_id=learner and course_slug='digital-income-online-work' and score>=70) or (select count(*) from lesson_progress where member_id=learner and lesson_slug like 'digital-income-lesson-%' and completed_at is not null)<>6 then raise exception 'Learner has not met course requirements';end if;insert into learning_certificates(member_id,course_slug,approved_by)values(learner,'digital-income-online-work',auth.uid())on conflict(member_id,course_slug)do nothing;update course_enrolments set completed_at=now() where member_id=learner and course_slug='digital-income-online-work';end$$;
revoke all on function public.submit_digital_income_knowledge_check(integer,jsonb),public.complete_digital_income_lesson(integer,jsonb,text),public.submit_digital_income_final_assessment(jsonb),public.approve_digital_income_assignment(uuid,text) from public;
grant execute on function public.submit_digital_income_knowledge_check(integer,jsonb),public.complete_digital_income_lesson(integer,jsonb,text),public.submit_digital_income_final_assessment(jsonb),public.approve_digital_income_assignment(uuid,text) to authenticated;
